Part3a datagen api
rpt09-orchid/meng-rooms pull request #10
Opened 2019-02-06 02:50 UTC by MengRS

Please test that postgres data can seed

2019-02-06 22:58 UTC, MengRS commented
@jondionowens, please repull - I fixed some merge issues.

2019-02-08 04:24 UTC, allenhsieh requested changes
Hey so quick note right out the gate, we're talking about this on slack but the initial seed command doesn't work because it's looking for a folder that doesn't exist

2019-02-08 04:56 UTC, allenhsieh requested changes

2019-02-08 04:56 UTC, allenhsieh commented on package.json
>      "start": "node server/server.js"
Hey Meng! This still start script refers to mongo code

2019-02-08 04:57 UTC, allenhsieh commented on package.json
>      "start": "node server/server.js"
![image](https://user-images.githubusercontent.com/10136383/52459616-0769db00-2b1b-11e9-9ee5-bd368233c22d.png)

2019-02-08 05:04 UTC, allenhsieh approved these changes
Approving + squash and merging.

Review of things we learned talked about:
1) `.gitkeep` is needed for git to track empty folders
2) the way the start script is right now, mongodb needed to be installed and running even though you're using postgres, consider separating it out or deleting

Just small comments, otherwise all good:
![image](https://user-images.githubusercontent.com/10136383/52459776-01c0c500-2b1c-11e9-8034-a6c6aff81447.png)

2019-02-08 05:05 UTC, merged